//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kbk_Jurnal
    {
        public int Id { get; set; }
        public int Number_kbk { get; set; }
        public string Rasshifrovka_kbk { get; set; }
        public string TipDeystviya { get; set; }
        public System.DateTime TimeChange { get; set; }
        public string KtoIzmenil { get; set; }
    }
}
