//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyEntities : DbContext
    {
        public MyEntities()
            : base("name=MyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kafedra> Kafedra { get; set; }
        public virtual DbSet<Kafedra_Jurnal> Kafedra_Jurnal { get; set; }
        public virtual DbSet<Kbk> Kbk { get; set; }
        public virtual DbSet<Kbk_Jurnal> Kbk_Jurnal { get; set; }
        public virtual DbSet<Kvr> Kvr { get; set; }
        public virtual DbSet<Kvr_Jurnal> Kvr_Jurnal { get; set; }
        public virtual DbSet<Sroc_zakupki> Sroc_zakupki { get; set; }
        public virtual DbSet<Sroc_zakupki_Jurnal> Sroc_zakupki_Jurnal { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Zakupka> Zakupka { get; set; }
        public virtual DbSet<Zakupka_Jurnal> Zakupka_Jurnal { get; set; }
    
        public virtual ObjectResult<string> RoleUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("RoleUser");
        }
    }
}
